//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyFilms.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolyFilms.Common.resLabels", typeof(resLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount In Words.
        /// </summary>
        public static string AmountInWords {
            get {
                return ResourceManager.GetString("AmountInWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approx Gross Weight (Kg).
        /// </summary>
        public static string AppGrossWeight {
            get {
                return ResourceManager.GetString("AppGrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer / Consignee .
        /// </summary>
        public static string BuyerConsignee {
            get {
                return ResourceManager.GetString("BuyerConsignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string BuyerId {
            get {
                return ResourceManager.GetString("BuyerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGST.
        /// </summary>
        public static string Cgst {
            get {
                return ResourceManager.GetString("Cgst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ChangeStatus.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee.
        /// </summary>
        public static string ConsigneeId {
            get {
                return ResourceManager.GetString("ConsigneeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core No.
        /// </summary>
        public static string CoreNo {
            get {
                return ResourceManager.GetString("CoreNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Weight (kg).
        /// </summary>
        public static string CoreWeight {
            get {
                return ResourceManager.GetString("CoreWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDelete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Schedule.
        /// </summary>
        public static string DeliverySchedule {
            get {
                return ResourceManager.GetString("DeliverySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Date.
        /// </summary>
        public static string DispatchDate {
            get {
                return ResourceManager.GetString("DispatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch No.
        /// </summary>
        public static string DispatchNo {
            get {
                return ResourceManager.GetString("DispatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEdit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Type.
        /// </summary>
        public static string FilmType {
            get {
                return ResourceManager.GetString("FilmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight (kg).
        /// </summary>
        public static string Grossweight {
            get {
                return ResourceManager.GetString("Grossweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number.
        /// </summary>
        public static string GSTNO {
            get {
                return ResourceManager.GetString("GSTNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGST.
        /// </summary>
        public static string Igst {
            get {
                return ResourceManager.GetString("Igst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInsert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is IGST ? .
        /// </summary>
        public static string IsIGSTInvoice {
            get {
                return ResourceManager.GetString("IsIGSTInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Invoice Generated.
        /// </summary>
        public static string IsInvoiceGenerated {
            get {
                return ResourceManager.GetString("IsInvoiceGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of joints.
        /// </summary>
        public static string Joint {
            get {
                return ResourceManager.GetString("Joint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint 1 Weight.
        /// </summary>
        public static string JointWeight1 {
            get {
                return ResourceManager.GetString("JointWeight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint 2 Weight.
        /// </summary>
        public static string JointWeight2 {
            get {
                return ResourceManager.GetString("JointWeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint 3 Weight.
        /// </summary>
        public static string JointWeight3 {
            get {
                return ResourceManager.GetString("JointWeight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo.
        /// </summary>
        public static string Jumbo {
            get {
                return ResourceManager.GetString("Jumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Date.
        /// </summary>
        public static string JumboDate {
            get {
                return ResourceManager.GetString("JumboDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Jumbo.
        /// </summary>
        public static string JumboJoint {
            get {
                return ResourceManager.GetString("JumboJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Joint 1.
        /// </summary>
        public static string JumboJointId1 {
            get {
                return ResourceManager.GetString("JumboJointId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Joint 2.
        /// </summary>
        public static string JumboJointId2 {
            get {
                return ResourceManager.GetString("JumboJointId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Joint 3.
        /// </summary>
        public static string JumboJointId3 {
            get {
                return ResourceManager.GetString("JumboJointId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Number.
        /// </summary>
        public static string JumboNo {
            get {
                return ResourceManager.GetString("JumboNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Remarks.
        /// </summary>
        public static string JumboStatusRemarks {
            get {
                return ResourceManager.GetString("JumboStatusRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (mtr).
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line No.
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Number.
        /// </summary>
        public static string Lrno {
            get {
                return ResourceManager.GetString("Lrno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Applications.
        /// </summary>
        public static string MainApplication {
            get {
                return ResourceManager.GetString("MainApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Features.
        /// </summary>
        public static string MainFeatures {
            get {
                return ResourceManager.GetString("MainFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Of Transport.
        /// </summary>
        public static string ModeOfTransport {
            get {
                return ResourceManager.GetString("ModeOfTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Transporter.
        /// </summary>
        public static string NameOfTransporter {
            get {
                return ResourceManager.GetString("NameOfTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Weight (kg).
        /// </summary>
        public static string Netweight {
            get {
                return ResourceManager.GetString("Netweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD (mtr).
        /// </summary>
        public static string Od {
            get {
                return ResourceManager.GetString("Od", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number.
        /// </summary>
        public static string PanNumber {
            get {
                return ResourceManager.GetString("PanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Contact Number.
        /// </summary>
        public static string PhoneNumber2 {
            get {
                return ResourceManager.GetString("PhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Treatment.
        /// </summary>
        public static string PreTreatment {
            get {
                return ResourceManager.GetString("PreTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Slitting.
        /// </summary>
        public static string PrimarySlitting {
            get {
                return ResourceManager.GetString("PrimarySlitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity (kg).
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Slitting Quantity(kg).
        /// </summary>
        public static string RemainingSlitting {
            get {
                return ResourceManager.GetString("RemainingSlitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set No..
        /// </summary>
        public static string SetNo {
            get {
                return ResourceManager.GetString("SetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGST.
        /// </summary>
        public static string Sgst {
            get {
                return ResourceManager.GetString("Sgst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Incharge.
        /// </summary>
        public static string ShiftIncharge {
            get {
                return ResourceManager.GetString("ShiftIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitting Date.
        /// </summary>
        public static string SlittingDate {
            get {
                return ResourceManager.GetString("SlittingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitting Joint 1.
        /// </summary>
        public static string SlittingJointId1 {
            get {
                return ResourceManager.GetString("SlittingJointId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitting Joint 2.
        /// </summary>
        public static string SlittingJointId2 {
            get {
                return ResourceManager.GetString("SlittingJointId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitting Joint 3.
        /// </summary>
        public static string SlittingJointId3 {
            get {
                return ResourceManager.GetString("SlittingJointId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitting Roll No.
        /// </summary>
        public static string SlittingRollNo {
            get {
                return ResourceManager.GetString("SlittingRollNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (m/min).
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        public static string TaxAmount {
            get {
                return ResourceManager.GetString("TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micron (μ).
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        public static string TimeIn {
            get {
                return ResourceManager.GetString("TimeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount With Tax.
        /// </summary>
        public static string TotalAmountWithTax {
            get {
                return ResourceManager.GetString("TotalAmountWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Rolls .
        /// </summary>
        public static string TotalRoll {
            get {
                return ResourceManager.GetString("TotalRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment.
        /// </summary>
        public static string Treatment {
            get {
                return ResourceManager.GetString("Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number.
        /// </summary>
        public static string VehicleNo {
            get {
                return ResourceManager.GetString("VehicleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsView.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Waste Weight.
        /// </summary>
        public static string WasteWeight {
            get {
                return ResourceManager.GetString("WasteWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (mm).
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winder.
        /// </summary>
        public static string Winder {
            get {
                return ResourceManager.GetString("Winder", resourceCulture);
            }
        }
    }
}
