//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyFilms.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resValidationMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resValidationMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolyFilms.Common.resValidationMsg", typeof(resValidationMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Address must be less than or equal to 100 characters..
        /// </summary>
        public static string AddressLength {
            get {
                return ResourceManager.GetString("AddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Address id required..
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer is required.
        /// </summary>
        public static string BuyerIdRequired {
            get {
                return ResourceManager.GetString("BuyerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGST is required.
        /// </summary>
        public static string CgstRequired {
            get {
                return ResourceManager.GetString("CgstRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must be same..
        /// </summary>
        public static string ConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee is required.
        /// </summary>
        public static string ConsigneeIdRequired {
            get {
                return ResourceManager.GetString("ConsigneeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Number must be less than or equat to 20 characters..
        /// </summary>
        public static string CoreNoLength {
            get {
                return ResourceManager.GetString("CoreNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Number is required.
        /// </summary>
        public static string CoreNoRequired {
            get {
                return ResourceManager.GetString("CoreNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core is required.
        /// </summary>
        public static string CoreRequired {
            get {
                return ResourceManager.GetString("CoreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address is Required.
        /// </summary>
        public static string DeliveryAddressRequired {
            get {
                return ResourceManager.GetString("DeliveryAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Schedule is required.
        /// </summary>
        public static string DeliveryScheduleRequired {
            get {
                return ResourceManager.GetString("DeliveryScheduleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Date is required.
        /// </summary>
        public static string DispatchDateRequired {
            get {
                return ResourceManager.GetString("DispatchDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address must be less than or equal to 100 characters..
        /// </summary>
        public static string EmailLength {
            get {
                return ResourceManager.GetString("EmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Type must be less than or equal to 50 characters.
        /// </summary>
        public static string FilmTypeLength {
            get {
                return ResourceManager.GetString("FilmTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Type is required.
        /// </summary>
        public static string FilmTypeRequired {
            get {
                return ResourceManager.GetString("FilmTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight is required.
        /// </summary>
        public static string GrossweightRequired {
            get {
                return ResourceManager.GetString("GrossweightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number must be less than or equal to 50 characters.
        /// </summary>
        public static string GSTNOLength {
            get {
                return ResourceManager.GetString("GSTNOLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number is required.
        /// </summary>
        public static string GSTNORequired {
            get {
                return ResourceManager.GetString("GSTNORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGST is required.
        /// </summary>
        public static string IgstRequired {
            get {
                return ResourceManager.GetString("IgstRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date is required.
        /// </summary>
        public static string InvoiceDateRequired {
            get {
                return ResourceManager.GetString("InvoiceDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Joint is required.
        /// </summary>
        public static string JointRequired {
            get {
                return ResourceManager.GetString("JointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo date is required.
        /// </summary>
        public static string JumboDateRequired {
            get {
                return ResourceManager.GetString("JumboDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is required.
        /// </summary>
        public static string LengthRequired {
            get {
                return ResourceManager.GetString("LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number must be only one characters.
        /// </summary>
        public static string LineNoLength {
            get {
                return ResourceManager.GetString("LineNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number is required.
        /// </summary>
        public static string LineNoRequired {
            get {
                return ResourceManager.GetString("LineNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location must be less than or equal to 50 characters.
        /// </summary>
        public static string LocationLength {
            get {
                return ResourceManager.GetString("LocationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required.
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location must be only one character.
        /// </summary>
        public static string LocationSlittingLength {
            get {
                return ResourceManager.GetString("LocationSlittingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Number is required.
        /// </summary>
        public static string LrnoRequired {
            get {
                return ResourceManager.GetString("LrnoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Applications must be less than or equal to 50 characters.
        /// </summary>
        public static string MainApplicationLength {
            get {
                return ResourceManager.GetString("MainApplicationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Applications are required.
        /// </summary>
        public static string MainApplicationRequired {
            get {
                return ResourceManager.GetString("MainApplicationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Features must be less than or equal to 50 characters.
        /// </summary>
        public static string MainFeaturesLength {
            get {
                return ResourceManager.GetString("MainFeaturesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Features are required.
        /// </summary>
        public static string MainFeaturesRequired {
            get {
                return ResourceManager.GetString("MainFeaturesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Of Transport is required.
        /// </summary>
        public static string ModeOfTransportRequired {
            get {
                return ResourceManager.GetString("ModeOfTransportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than or equal to 50 characters.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Transporter is required.
        /// </summary>
        public static string NameOfTransporterRequired {
            get {
                return ResourceManager.GetString("NameOfTransporterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD is required.
        /// </summary>
        public static string OdRequired {
            get {
                return ResourceManager.GetString("OdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is required.
        /// </summary>
        public static string OperatorRequired {
            get {
                return ResourceManager.GetString("OperatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date is required.
        /// </summary>
        public static string OrderDateRequired {
            get {
                return ResourceManager.GetString("OrderDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is required.
        /// </summary>
        public static string OrderRequired {
            get {
                return ResourceManager.GetString("OrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number must be less than or equal to 50 characters.
        /// </summary>
        public static string PanNumberLength {
            get {
                return ResourceManager.GetString("PanNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number is required.
        /// </summary>
        public static string PanNumberRequired {
            get {
                return ResourceManager.GetString("PanNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than or equal to 15 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number must be less than or equal to 20 characters..
        /// </summary>
        public static string PhoneNumberLength {
            get {
                return ResourceManager.GetString("PhoneNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number is required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Treatment must be less than or equal to 50 characters.
        /// </summary>
        public static string PreTreatmentLength {
            get {
                return ResourceManager.GetString("PreTreatmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Treatment is required.
        /// </summary>
        public static string PreTreatmentRequired {
            get {
                return ResourceManager.GetString("PreTreatmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is required.
        /// </summary>
        public static string ProductRequired {
            get {
                return ResourceManager.GetString("ProductRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality is required.
        /// </summary>
        public static string QualityRequired {
            get {
                return ResourceManager.GetString("QualityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is required.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions must be lessa than or equal to 500 characters.
        /// </summary>
        public static string RemarksLength {
            get {
                return ResourceManager.GetString("RemarksLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than or equal to 50 characters.
        /// </summary>
        public static string RoleNameLength {
            get {
                return ResourceManager.GetString("RoleNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set No is required.
        /// </summary>
        public static string SetNoRequired {
            get {
                return ResourceManager.GetString("SetNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGST is required.
        /// </summary>
        public static string SgstRequired {
            get {
                return ResourceManager.GetString("SgstRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Incharge is required..
        /// </summary>
        public static string ShiftInchargeRequired {
            get {
                return ResourceManager.GetString("ShiftInchargeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift is required.
        /// </summary>
        public static string ShiftRequired {
            get {
                return ResourceManager.GetString("ShiftRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitting date is required.
        /// </summary>
        public static string SlittingDateRequired {
            get {
                return ResourceManager.GetString("SlittingDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micron is required.
        /// </summary>
        public static string ThicknessRequired {
            get {
                return ResourceManager.GetString("ThicknessRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeIn is required.
        /// </summary>
        public static string TimeInRequired {
            get {
                return ResourceManager.GetString("TimeInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOut is required.
        /// </summary>
        public static string TimeOutRequired {
            get {
                return ResourceManager.GetString("TimeOutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is required.
        /// </summary>
        public static string TreatmentRequired {
            get {
                return ResourceManager.GetString("TreatmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name must be less than or equal to 50 characters.
        /// </summary>
        public static string UsernameLength {
            get {
                return ResourceManager.GetString("UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle No is required.
        /// </summary>
        public static string VehicleNoRequired {
            get {
                return ResourceManager.GetString("VehicleNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is required.
        /// </summary>
        public static string WeightRequired {
            get {
                return ResourceManager.GetString("WeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width is required.
        /// </summary>
        public static string WidthRequired {
            get {
                return ResourceManager.GetString("WidthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winder must be only one character.
        /// </summary>
        public static string WinderLength {
            get {
                return ResourceManager.GetString("WinderLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winder is required.
        /// </summary>
        public static string WinderRequired {
            get {
                return ResourceManager.GetString("WinderRequired", resourceCulture);
            }
        }
    }
}
